sopt-makers/sopt-operation-backend

src/main/java/org/sopt/makers/operation/controller/HealthCheckController.java
src/main/java/org/sopt/makers/operation/entity/Attendance.java
src/main/java/org/sopt/makers/operation/entity/AttendanceStatus.java
src/main/java/org/sopt/makers/operation/entity/Part.java
src/main/java/org/sopt/makers/operation/entity/Session.java
src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
src/main/java/org/sopt/makers/operation/entity/SubSession.java

[FEAT] 출석 관련 Entity 설계 및 생성

---

src/main/java/org/sopt/makers/operation/entity/Attendance.java
src/main/java/org/sopt/makers/operation/entity/Lecture.java
src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
src/main/java/org/sopt/makers/operation/entity/SubLecture.java

closed #21 
- 서버 내에서 Session 용어 중복 사용으로 인해 Lecture로 Entity명 변경
- 빠진 곳 없겠죵?

[FIX] Session Entity명 변경

---

build.gradle
src/main/java/org/sopt/makers/operation/controller/AdminController.java
src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
src/main/java/org/sopt/makers/operation/dto/admin/LoginRequestDTO.java
src/main/java/org/sopt/makers/operation/dto/admin/LoginResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/admin/SignUpRequestDTO.java
src/main/java/org/sopt/makers/operation/dto/admin/SignUpResponseDTO.java
src/main/java/org/sopt/makers/operation/entity/Admin.java
src/main/java/org/sopt/makers/operation/entity/AdminStatus.java
src/main/java/org/sopt/makers/operation/entity/Role.java
src/main/java/org/sopt/makers/operation/exception/AdminFailureException.java
src/main/java/org/sopt/makers/operation/exception/TokenException.java
src/main/java/org/sopt/makers/operation/repository/AdminRepository.java
src/main/java/org/sopt/makers/operation/security/config/SecurityConfig.java
src/main/java/org/sopt/makers/operation/security/jwt/AdminAuthentication.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenType.java
src/main/java/org/sopt/makers/operation/service/AdminService.java
src/main/java/org/sopt/makers/operation/service/AdminServiceImpl.java
src/main/resources/application.yml

- #17 
- 피드백 해준 부분 수정
- 이슈 공유, 대응 공유

[FEAT] 임원진 로그인 구현, PR반영 #17

---

src/main/java/org/sopt/makers/operation/entity/Gender.java
src/main/java/org/sopt/makers/operation/entity/Member.java
src/main/java/org/sopt/makers/operation/entity/ObYb.java

closed #25 
- Member 엔티티 추가
운영팀에서 따로 관리하는 Member 엔티티를 추가했습니다.

[CHORE] Member Entity 추가

---

build.gradle
src/main/java/org/sopt/makers/operation/config/SwaggerConfig.java
src/main/java/org/sopt/makers/operation/controller/AdminController.java
src/main/java/org/sopt/makers/operation/controller/HealthCheckController.java
src/main/java/org/sopt/makers/operation/controller/LectureController.java

closed #37 
스웨거 붙였습니다!
추가 필요한 사항 있을지 확인 부탁드려요~!

[CHORE] Swagger 추가

---

src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/LectureController.java
src/main/java/org/sopt/makers/operation/dto/lecture/AttendanceVO.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureVO.java
src/main/java/org/sopt/makers/operation/entity/Part.java
src/main/java/org/sopt/makers/operation/entity/lecture/Attribute.java
src/main/java/org/sopt/makers/operation/repository/AttendanceRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepository.java
src/main/java/org/sopt/makers/operation/service/LectureService.java
src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

closed #34 
- 세션 전체 리스트 조회 (+ 기수 필터링)

[FEAT] 세션 전체 리스트 조회

---

src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
src/main/java/org/sopt/makers/operation/controller/LectureController.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/lecture/LecturesResponseDTO.java
src/main/java/org/sopt/makers/operation/entity/Attendance.java
src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
src/main/java/org/sopt/makers/operation/service/LectureService.java
src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

closed #36 
- 세션 상세 조회입니다.
```
{
"success": true,
"message": "세션 상세 조회 성공",
"data": {
"name": "테스트",
"generation": 32,
"part": "SERVER",
"attribute": "SEMINAR",
"members": [
{
"name": "소현",
"university": "앙중대",
"attendances": [
{
"round": 1,
"status": "ABSENT",
"date": null
},
{
"round": 2,
"status": "ABSENT",
"date": null
}
],
"score": 0.0
},
{
"name": "용택",
"university": "숭실숭실",
"attendances": [
{
"round": 1,
"status": "ABSENT",
"date": null
},
{
"round": 2,
"status": "ABSENT",
"date": null
}
],
"score": 0.0
}
]
}
}
```

[FEAT] 세션 상세 조회 기능 구현

---

src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceRequestDTO.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceResponseDTO.java
src/main/java/org/sopt/makers/operation/entity/Member.java
src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
src/main/java/org/sopt/makers/operation/repository/SubAttendanceRepository.java
src/main/java/org/sopt/makers/operation/service/AttendanceService.java
src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java

closed #42 
- 출석 점수를 변경하는 기능을 구현했습니다.

[FEAT] 출석 점수 변경 기능 구현

---

src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/config/GenerationConfig.java
src/main/java/org/sopt/makers/operation/controller/AppController.java
src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseVO.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseType.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureSearchCondition.java
src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
src/main/java/org/sopt/makers/operation/exception/LectureException.java
src/main/java/org/sopt/makers/operation/exception/MemberException.java
src/main/java/org/sopt/makers/operation/repository/AttendanceRepository.java
src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepository.java
src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenType.java
src/main/java/org/sopt/makers/operation/service/LectureService.java
src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
src/main/java/org/sopt/makers/operation/service/MemberService.java
src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
src/main/resources/application.yml

- #32
- 단일 세션 정보 가져옵니다
1. 앱팀 토큰 활용 방식 
2. subattendance의 last_modified_date를 출석 시점으로 확인하면 되는지?(ATTENDANCE 일 경우)

[FEAT] 단일 세션 가져오기

---

src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/AppController.java
src/main/java/org/sopt/makers/operation/dto/member/MemberScoreGetResponse.java

- #49 
- 앱팀에서 사용할 출석 점수 조회 기능입니다
- 간단한 기능이라 크게 없을것 같아요

[FEAT] 출석 점수 조회 기능 #49

---

src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
src/main/java/org/sopt/makers/operation/entity/AttendanceStatus.java
src/main/java/org/sopt/makers/operation/service/AttendanceService.java
src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java

closed #52 
- 임원진이 유저별 출석 정보 조회를 확인할 수 있습니다.

[FEAT] 유저별 출석 정보 조회: 웹

---

src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/AppController.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalCountVO.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceTotalVO.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
src/main/java/org/sopt/makers/operation/service/LectureService.java
src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

[FEAT] 전체 출석 정보 가져오기

---

src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java

closed #56 
- 세션별 추가 점수 데이터 추가해쒀요. 놓치고 한번에 못해서 미안함다 ㅠㅠ

[ADD] 세션별 추가점수 데이터 추가

---

src/main/java/org/sopt/makers/operation/controller/AppController.java

- #58 
- 스웨거 정보를 추가하였습니다
- 스웨거 403이 계속 뜨는데 한번 같이 봐주실 수 있나요?
- 안쓰는 query paramenter가 넣어져있어요

[FIX] 스웨거 정보 추가 

---

src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java

closed #81 
- 회원 파트 필터링 쿼리 수정했습니다.
proxy 이슈로 Entity를 받아오지 못한 쿼리를 수정했습니다.

[FIX] 회원 파트 필터링 쿼리 수정

---

src/main/java/org/sopt/makers/operation/controller/AdminController.java
src/main/java/org/sopt/makers/operation/dto/admin/RefreshResponseDTO.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java
src/main/java/org/sopt/makers/operation/service/AdminService.java
src/main/java/org/sopt/makers/operation/service/AdminServiceImpl.java

- #78 
- 앱팀 토큰 변화에 맞춰 playGroundId를 사용했습니다
- 쿠키를 이용해서 refreshToken을 반환합니다
- 쿠키를 이용해서 토큰을 갱신합니다

[FEAT] 앱 토큰에 맞춰 변환, 쿠키 리프레시 토큰

---

src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/AppController.java
src/main/java/org/sopt/makers/operation/controller/ExceptionController.java
src/main/java/org/sopt/makers/operation/controller/LectureController.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendRequestDTO.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/lecture/LectureCurrentRoundResponseDTO.java
src/main/java/org/sopt/makers/operation/entity/SubLecture.java
src/main/java/org/sopt/makers/operation/exception/SubLectureException.java
src/main/java/org/sopt/makers/operation/repository/lecture/SubLectureRepository.java
src/main/java/org/sopt/makers/operation/service/AttendanceService.java
src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
src/main/java/org/sopt/makers/operation/service/LectureService.java
src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

- #80 
- 출석하기 기능입니다
- 출석(subLecture) 정보 가져오기
- 그것을 기반으로 출석하기
- code 필드 추가 
- 10분 안으로만 출석 가능합니다

[FEAT] 출석 기능 

---

src/main/java/org/sopt/makers/operation/dto/attendance/AttendRequestDTO.java
src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/attendance/MemberInfo.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepository.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java

[REFACT] 쿼리 최적화

---

src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseVO.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

- #98
- 현재 세미나 감추기
- 프로그레스바 로직

[FIX] 현재 세미나 감추기, 프로그레스바 #98

---

src/main/java/org/sopt/makers/operation/entity/BaseEntity.java

closed #103 
- UTC 관련 에러를 수정합니다.
- BaseEntity에서 timezone을 추가했습니다.

[FIX] UTC 관련 이슈 수정

---

src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java

closed #105 
- 출석 결과 정보를 추가했습니다.

[ADD] 출석 결과 정보 추가

---

src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceMemberResponseDTO.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java

- 실서버 배포
- 회원 출석 내역 조회: 출석 결과 정보 추가
- 세션 출석 내역 조회: 페이지네이션 임시 삭제

[DEPLOY] 실서버 배포

---

src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java

- closed #107 
- 세션 내 출결 상태 조회에서 페이지네이션 활성화
- 충돌 및 변경 커밋 중복을 고려하여 117번 브랜치로 PR 하겠습니다.

[FIX] 페이지네이션 활성화

---

src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java

- closed #120 
- 회원 출석 내역 조회에서, 정렬 기준 변경했습니다~!

[FIX] 회원 출석 내역 조회: 정렬 기준 변경

---

src/main/java/org/sopt/makers/operation/security/jwt/JwtAuthenticationFilter.java
src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java

- #112
- 리프레시 토큰 클라이언트 테스트를 위한 만료시간 조정 (3분)
- auth 리팩토링 시작할 예정입니다. 우선 만료시간 조정이 급해서 해놓고 리팩토링 따로 파서 할 예정입니다!

리프레시 테스트용 토큰 만료시간 조정 #112

---

src/main/java/org/sopt/makers/operation/security/jwt/JwtTokenProvider.java

- #134
- 엑세스 토큰 시간 복구 3min -> 5hour

[CHORE] 엑세스 토큰 시간 복구 #134

---

src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/InternalOpenApiController.java
src/main/java/org/sopt/makers/operation/controller/app/AppMemberController.java
src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
src/main/java/org/sopt/makers/operation/entity/Member.java
src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
src/main/java/org/sopt/makers/operation/service/MemberService.java
src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java

- closed #142 
- 회원 등록 API 개발
- 09.11 22:01 기준 API 수정했습니다!
- 플레이그라운드팀으로부터 API 요청을 받는 것으로 변경
- 플레이그라운드 요청임을 확인하기 위해 `x-api-key`와 `x-request-from` 헤더 값을 추가 및 검증
- 플그 id는 중복될 수 없으므로 Unique 추가 처리했습니다!
- 테스트 완료했습니다 :)
<br/>

[FEAT] 회원 등록 API

---

src/main/java/org/sopt/makers/operation/security/config/SecurityConfig.java

- closed #147 
- production 서버의 swagger 접근을 제한합니다.

[DEL] 스웨거 제한

---

src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

- #137
- 단일 라운드 조회를 리팩토링 했습니다.
- 가독성이 좋아지게 개발 시점에는 없던 field인 lecture의 status를 사용하였습니다!

[FIX] 단일 라운드 조회 리팩토링

---

src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
src/main/java/org/sopt/makers/operation/entity/Member.java

- closed #149 
- 성별 데이터 생략 (운영팀에서 수기 추가 필요)

[FIX] Gender 데이터 생략

---

.github/PULL_REQUEST_TEMPLATE.md

- closed #153 
- `Related Issue` 내용에 `closed` 추가
- PR 머지 후 이슈가 자동으로 닫히도록 합니다.

[DOCS] PR 템플릿 수정

---

src/main/java/org/sopt/makers/operation/entity/Member.java

- closed #160 
- 기수가 올라가면서 OB 회원은 새로운 데이터를 만들기로 결정됨에 따라 Unique 속성을 제거합니다.

[DEL] 플그 id Unique 속성 삭제

---

src/main/java/org/sopt/makers/operation/dto/lecture/LectureDetailResponseDTO.java

- closed #164 
- FE 요청에 따라 응답 값에 generation 필드를 추가했습니다.

[ADD] 세션 상세 조회: 응답 값 추가

---

src/main/java/org/sopt/makers/operation/converter/LongListConverter.java
src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
src/main/java/org/sopt/makers/operation/dto/member/MemberRequestDTO.java
src/main/java/org/sopt/makers/operation/entity/Gender.java
src/main/java/org/sopt/makers/operation/entity/Member.java
src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
src/main/java/org/sopt/makers/operation/entity/alarm/Attribute.java
src/main/java/org/sopt/makers/operation/entity/alarm/Status.java
src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java

- closed #169 
- Member 엔티티에서 사용하지 않는 Gender 칼럼을 삭제했습니다.
- 출석 이름 정렬 방식을 수정했습니다. (2글자가 3글자보다 앞에 오는 이슈)
- 알림 엔티티를 추가했습니다.
- 현재 위 사항들은 dev DB에 적용된 상태입니다. (prod DB 적용X)
- 스프린트1 종료 기간에 맞춰 develop 서버 반영 후 prod 서버 및 DB도 반영할 예정입니다.
- 특히 알림 Entity 부분에서 빠진 칼럼은 없는 지, 수정할 부분은 없는 지, 칼럼명에 대한 이견 등등 있다면 리뷰 부탁드려요!

[CHORE] Entity 추가 설계

---

src/main/java/org/sopt/makers/operation/service/AlarmService.java
src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

- closed #176 
- 세션 종료 후 알림 발송 기능을 추가했습니다.

[ADD] 세션 종료 후 알림 발송 추가

---

src/main/java/org/sopt/makers/operation/converter/StringListConverter.java
src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java

- closed #178 
- targetList 타입 변경

[FIX] 컨버터 수정

---

src/main/java/org/sopt/makers/operation/controller/ScheduleController.java

[FIX] 요일 값 수정

---

src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

- closed #{이슈_번호}
- production 서버 배포

[CHORE] SP1 prod 서버 반영

---

src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java

[CHORE] 실서버 배포

---

src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java

- closed #187 
- 알림 생성 시 기수와 파트 null 처리를 분리합니다.

[FIX] 알림 생성 : null 처리 분리

---

src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java

[FIX] 알림 어드민 발송 필터 및 전송 시간 에러 수정

---

src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
src/main/java/org/sopt/makers/operation/dto/lecture/LecturesResponseDTO.java

- closed #191 
- 클라이언트 추가 요구사항 반영입니다.
- GET `/api/v1/lectures` : 장소, 종료시간 추가
- GET `/api/v1/attendances/lecture/{lectureId}` : 각 멤버 파트 추가

[ADD] 응답 데이터 추가

---

src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java

- closed #193 
- 생성된 시점의 기수 정보를 저장하기 위한 칼럼을 추가했습니다.

[ADD] 생성 기준 기수 칼럼 추가

---

src/main/java/org/sopt/makers/operation/dto/admin/LoginResponseDTO.java
src/main/java/org/sopt/makers/operation/entity/AdminStatus.java

- closed #197
- 로그인시 권한을 반환합니다
- 권한명: MAKERS, SOPT

[ADD] 로그인시 권한 반환 추가

---

scripts/health_check.sh
src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
src/main/java/org/sopt/makers/operation/controller/app/AppScheduleController.java
src/main/java/org/sopt/makers/operation/dto/schedule/SchedulesResponseDTO.java
src/main/java/org/sopt/makers/operation/entity/schedule/Schedule.java
src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleCustomRepository.java
src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepository.java
src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepositoryImpl.java
src/main/java/org/sopt/makers/operation/service/ScheduleService.java
src/main/java/org/sopt/makers/operation/service/ScheduleServiceImpl.java

- closed #216 
- prod단 CD시 health-check 실패에 대한 수정
- prod용 log 추가로 인한 nohup 가동 시간이 더 늘어나서 가동되기 이전에 fail이 나는 것으로 추정 중
- 테스트 후 원인이 확정된다면 시간 조정 예정

[FIX] health check 소요 시간 추가

---

operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java
operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
scripts/health_check.sh

[FIX] 테스트 경로 추가

---

operation-api/src/main/java/org/sopt/makers/operation/app/attendance/service/AppAttendanceServiceImpl.java
operation-api/src/main/java/org/sopt/makers/operation/app/lecture/dto/response/TodayLectureResponse.java
operation-api/src/main/java/org/sopt/makers/operation/app/lecture/service/AppLectureServiceImpl.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApiController.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/request/SignUpRequest.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/LoginResponse.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/RefreshResponse.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/SignUpResponse.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/response/TokenRefreshGetResponse.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminService.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminServiceImpl.java
operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
operation-domain/build.gradle
operation-domain/src/main/java/org/sopt/makers/operation/admin/domain/Admin.java

- closed #238
- 테스트를 하며 생긴 500 이슈를 해결하였습니다.
- 리팩토링 도중 없어졌던 로직을 추가하였습니다.
- 리팩토링을 추가로 진행하였습니다.
- 논의할만한 부분 코멘트로 남겨놨습니다.

[FIX] 테스트 중 500 에러 수정 + 추가 리팩토링

---

operation-domain/src/main/java/org/sopt/makers/operation/attendance/domain/Attendance.java

HOT FIX() : 34기 출석 점수 연산 방식 수정 반영

---

operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java
operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
operation-domain/src/main/java/org/sopt/makers/operation/auth/domain/TeamOAuthInfo.java

- closed #263 
- 클라이언트의 배포 도메인 변경에 따라 legacy 주소 관련 코드를 제거했습니다.
- 깃허브 액션 시크릿키 변경 해두었습니다.

#263 [CHORE] Legacy Url 관련 코드 삭제

---

operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApi.java
operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java

- closed #266 
Security 내 SSO 기반 인증 End Point 등록

#266_T-10860 [feat] Security 내 SSO 기반 인증 End Point 등록

---

.github/workflows/cd-dev.yml
appspec.yml
scripts/run_new_was.sh
scripts/switch.sh

- closed #251
- CD 시, 스크립트를 돌리는 사용자 계정을 변경해서 권한 문제를 해결합니다.

[FIX] 로그 파일 권한 문제로 발생하는 스크립트 오류 수정

---

README.md

[DOCS] README.md 정보 최신화

---

.dockerignore
.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml
.gitignore
Dockerfile
appspec.yml

- closed #284 
- 단일 EC2 내 다중 어플리케이션 구동을 위한 Docker 환경 마이그레이션에 따라 프로젝트 구성 파일을 편집했습니다.

[REFACTOR] Docker 환경 이전 (#284)

---

.github/workflows/cd-dev.yml

[MODIFY] transfer 한 file mv 명령에 sudo 추가

---

operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java

- closed #304
- 쿼리 파라미터 변수명 컨벤션을 맞추었습니다!
- 컨벤션 통일이라 수정 부분이 적습니다 ㅎ

[FEAT] PreSignedUrl 발급 API의 쿼리파라미터 네이밍 snake로 변경

---

.gitignore
operation-api/src/main/java/org/sopt/makers/operation/common/config/SwaggerConfig.java
operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtExceptionFilter.java
operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtTokenProvider.java

- closed #307 
- Postman Mock 서버 및 http 스웨거만 사용하던 현재 API 테스트에서 https를 붙여 스웨거 활성화
- Dev 통합 인스턴스 서버 로그 확인을 위한 코드 추가

feat : 스웨거 https 세팅 및 authentication 로그  추가

---

operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java

- closed #315 
- 진행 종료된 배너 수정 및 삭제 불가 작업 추가

[Feat] 배너 어드민 진행 종료된 배너 수정 및 삭제 불가 작업 추가

---

operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ContentType.java
operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishLocation.java

- closed #315 
- 배너 위치 및 컨텐츠 타입의 케이스가 좁아서 수정.

[FEAT] 배너 위치 및 컨텐츠 타입 수정

---

.github/workflows/cd-prod.yml

- related #317 
- cd-prod 오타 수정

[INFRA] cd-prod 오타 수정

---

operation-api/src/main/resources/application-prod.yml

[INFRA] 환경 변수 CD 파이프라인 수정

---

operation-api/src/main/java/org/sopt/makers/operation/common/config/WebConfig.java

- related to #324 
- PATCH 출석시작하기 CORS 수정

[FIX] 출석 시작하기 CORS 수정

---

operation-api/src/main/java/org/sopt/makers/operation/common/config/WebConfig.java

[FIX] CORS 오타 수정

---

operation-api/src/main/java/org/sopt/makers/operation/common/config/WebConfig.java

[FIX] cors 오타2

---

operation-api/src/main/java/org/sopt/makers/operation/common/config/WebConfig.java

[FIX] 불필요한 오타 수정

---

operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java

[FIX] ROLLBACK CROS

---

operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java

- related to #315 
- 배너 목록조회 정렬 수정

[FIX] 배너 조회 시작 정렬 수정

---

operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java

- related to #315 
- 배너 목록 api 파라미터 수정

[FIX] 배너 목록 조회 api 파라미터명 수정

---

operation-api/src/main/java/org/sopt/makers/operation/web/lecture/service/WebLectureServiceImpl.java
operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java

[FIX] : yml파일(env)로 관리하는 한글 문자열 코드 내부로 이동

---

operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApi.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/api/AdminApiController.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/dto/request/PasswordChangeRequest.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminService.java
operation-api/src/main/java/org/sopt/makers/operation/web/admin/service/AdminServiceImpl.java
operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
operation-common/src/main/java/org/sopt/makers/operation/code/success/web/AdminSuccessCode.java

- related to #337 
- 비밀번호 변경 api 추가

[FEAT] 비밀번호 변경 api 추가

---

operation-external/src/main/java/org/sopt/makers/operation/client/alarm/InstantAlarmSender.java

- closed #344 
- related to #344
- 알림 서버에 즉시 알림 요청 시 body 필드명 appLink -> deepLink로 오타 수정

[FIX] 알림 서버에 즉시 알림 요청 시 body 필드명 appLink -> deepLink로 오타 수정

---

operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
operation-common/src/main/java/org/sopt/makers/operation/constant/AlarmConstant.java

- closed #347 
- related to #347
- 누락된 deepLink 리스트 추가

[FIX] 누락된 deepLink 리스트 추가

---

operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmInstantSendRequest.java
operation-api/src/main/java/org/sopt/makers/operation/web/alarm/dto/request/AlarmScheduleSendRequest.java
operation-domain/src/main/java/org/sopt/makers/operation/alarm/domain/AlarmTarget.java

- closed #349 
- related to #349
모든 알림 생성 요청에 대해 createdGeneration 저장하도록 수정

[FIX] 모든 알림 생성 요청에 대해 createdGeneration 저장하도록 수정

---

operation-api/src/main/java/org/sopt/makers/operation/common/handler/ErrorHandler.java
operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
operation-auth/src/main/java/org/sopt/makers/operation/config/SecurityConfig.java
operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java

- related to #353 
-  게시중인 외부 배너 리스트 조회 API image_type 없이 모든 타입 반환하도록 수정

[FEAT] 외부 배너 리스트 조회 API 수정

---

operation-api/src/main/resources/application-prod.yml

feat : 개행 오타 수정

---

operation-api/src/main/java/org/sopt/makers/operation/app/member/api/AppMemberApiController.java
operation-api/src/main/resources/application-prod.yml

2 [Merge] develop -> main 2025/08/30 

---

operation-api/src/main/resources/application-prod.yml

3[Merge] develop -> main 2025/08/30 

---

.github/workflows/cd-dev.yml
.github/workflows/cd-prod.yml

feat : 배포 스크립트에 ecr 이미지 삭제추가
