sopt-makers/sopt-operation-backend

- scripts/health_check.sh
- src/main/java/org/sopt/makers/operation/controllers/HealthCheckController.java
- #5
- Let's Encrypt를 통해 SSL을 붙이는 과정에서 문제가 발생함
- 루트 경로에 반환값을 설정해주지 않는 바람에 404를 띄우고 있어서 그럼
- Let's Encrypt가 루트 경로인 `operation.api.dev.sopt.org`에 요청했는데 404를 받아서 우리에게 발급해주지 않음
- 그래서 루트 경로가 200을 간단하게 반환하도록 변경함
- 근데 배포시에도 health_check를 하니까, 똑같은 것을 사용하면 될 것이라서 배포 스크립트도 수정해놓음 
너무 사소한것이라, 크게 받을 부분은 없을것 같아요! 문서화를 잘 해놓겠습니다!
> [FIX]: healthCheck root 경로로 변경

- src/main/java/org/sopt/makers/operation/config/JpaAuditingConfig.java
- src/main/java/org/sopt/makers/operation/entity/BaseEntity.java
- src/main/java/org/sopt/makers/operation/entity/Session.java
- src/main/java/org/sopt/makers/operation/entity/SubAttendance.java
closed #13 
- Entity 관련해서 추가 작업 진행했습니다.
- Session 엔티티에 generation 칼럼 추가 -> 기수 관련 정보가 필요할 것으로 판단함
- SubAttendace 엔티티의 isCheck 칼럼을 status 칼럼으로 변경 -> 출석의 여부보다 상태를 칼럼으로 가지는 것이 더 유연할 것으로 판단함
- 타입: AttendaceStatus
- BaseEntity 추가 -> 생성 및 수정 날짜 데이터가 필요할 것으로 판단
- 이에 따라 전체적으로 필요한 어노테이션을 추가하기 위해 JpaAuditingConfig 파일 추가
- Session 엔티티에 대표 보기용으로 BaseEntity 확장함.
> [FIX] Entity 추가 설정

- src/main/java/org/sopt/makers/operation/entity/SubSession.java
- #15 
- `SubSession entity`의 컬럼명인 `order`를 `round`로 변경하였습니다
- PostgreSQL에서 order라는 field를 사용하면 오류가 발생
- https://www.postgresql.org/docs/current/sql-keywords-appendix.html
- 따라서 대안으로 round라는 필드로 변경
> [FIX] 필드명 오류 수정

- src/main/java/org/sopt/makers/operation/common/ApiResponse.java
closed #19 
- success와 fail 응답 데이터 형식을 지정했습니다.
- success 사용 방식
```
@GetMapping("/test/success")
public ResponseEntity<Object> testSuccessApiResponse() {
ApiResponse response = ApiResponse.success("test message", "data");
return ResponseEntity.ok(response);
}
```
- fail 사용 방식 (예외처리 컨트롤러에서 해당 방식 적용이 필요합니다.)
```
@GetMapping("/test/fail")
public ResponseEntity<Object> testFailApiResponse() {
ApiResponse response = ApiResponse.fail("test message");
return new ResponseEntity<>(response, HttpStatus.NOT_FOUND);
}
```
- 기존 SOPT에서 사용하던 응답 메세지에서 status 코드는 응답 메세지에 포함시키지 않아도 전달할 수 있어서 제외했습니다.
- 그 외에 성공 여부(success), 응답 메세지(message), 응답 데이터(data) 항목을 포함했습니다.
> [CHORE] 공통 ApiResponse 추가

- src/main/java/org/sopt/makers/operation/dto/attendance/AttendanceResponseDTO.java
- src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
- src/main/java/org/sopt/makers/operation/entity/Attendance.java
- src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
closed #48 
- N차 출석 상태를 변경할 때, 해당 전체 출석 상태를 업데이트하는 로직을 추가했습니다.
- 기존 2차 출석을 변경해야만 유저의 점수를 변경했던 로직에서 -> 출석 변경만 하면 유저의 점수를 변경하는 로직으로 변경했습니다.
로직 수정하는 김에 switch 문에서 {}을 제외했는데 요렇게 뜨더라구요ㅠㅠ 전에 코드리뷰 중 말한 사항입니다!
> [FIX] 출석 상태 게산 로직 변경

- src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
- src/main/java/org/sopt/makers/operation/entity/Member.java
- src/main/java/org/sopt/makers/operation/service/AttendanceService.java
- src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
closed #63 
- 유저 출석 점수를 전체 갱신하는 트리거 역할하는 API를 구현했습니다.
> [FEAT] 유저 출석 점수 갱신 기능 구현

- src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
- src/main/java/org/sopt/makers/operation/util/Generation32.java
closed #64 
- N차 출석 상태 변경 시, 출석(Attendance) 상태 변경 로직을 추가했습니다.
출석 상태를 판단하는 로직이 끊임없이 나올 것 같아서 util.Generation32 클래스를 생성하고 해당 로직을 추가했습니다.
아래 로직이 괜찮다면, 리팩토링 기간에 퍼져있는 같은 로직 수습 좀 하겠읍니다 😇
```
public AttendanceStatus getAttendanceStatus(Attribute attribute, List<SubAttendance> subAttendances) {
int firstRound = subAttendances.get(0).getSubLecture().getRound() == 1 ? 0 : 1;
SubAttendance first = subAttendances.get(firstRound);
SubAttendance second = subAttendances.get(1 - firstRound);
return switch (attribute) {
case SEMINAR -> getAttendanceStatusInSeminar(first, second);
case EVENT -> getAttendanceStatusInEvent(second);
case ETC -> getAttendanceStatusInEtc(second);
};
}
```
또한, 현재 해당 로직(출석 상태 변경)에서 쿼리가 6개까지 나가고 있어요 ㅠㅅㅠ 리팩토링 기간에 최적화 방안까지 생각해보도록 하겟읍니다..
> [ADD] 출석 상태 변경 로직 추가

- src/main/java/org/sopt/makers/operation/dto/lecture/LectureGetResponseDTO.java
- src/main/java/org/sopt/makers/operation/service/LectureService.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
- #71 
- ETC, 행사일시 메세지를 추가로 반환합니다
- 출석 점수가 반영되지 않아요. / 행사도 참여하고, 출석점수도 받고, 일석이조!
- 행사시에도 출석 정보 반환하도록함
- val 사용
- val을 사용하고 싶은데, 케이스마다 구분된 (세미나 1개인날, 2개인날(솝커톤-세미나)) scope 안에서 재할당해야하는 변수들이라 final인 val이 안먹습니다. val을 사용하면서 깔끔하게 할 방법이 있을까요?
```
Lecture currentSession;
LectureResponseType type;
```
> [FIX] 단일 세미나 로직 변경

- src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
- src/main/java/org/sopt/makers/operation/controller/AttendanceController.java
- src/main/java/org/sopt/makers/operation/controller/LectureController.java
- src/main/java/org/sopt/makers/operation/dto/attendance/MemberResponseDTO.java
- src/main/java/org/sopt/makers/operation/dto/lecture/AttendanceRequestDTO.java
- src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
- src/main/java/org/sopt/makers/operation/entity/SubLecture.java
- src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/service/AttendanceService.java
- src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
- src/main/java/org/sopt/makers/operation/service/LectureService.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
- src/main/java/org/sopt/makers/operation/util/Generation32.java
closed #84 
- 세션 상세 조회 기능 분리: part 쿼리를 삭제 (출석 리스트에서 반영 필요)
- SubLecture 출석 코드 추가
- 세션 출석 정보 리스트 조회 기능 추가: 페이징 처리 (page: 페이지 번호, size: 페이지 당 데이터 개수)
- 토큰 유효성은 filter 에서 확인해주는 것으로 인지하고 confirmAdmin의 필요성에 대해 의구심을 가지게 되면서 삭제했습니다. 의논해보면 좋을 것 같아요!
- ApiResponses 어노테이션 코드가 차지하는 공간이 커서 코드가 복잡해보이더라구요. 우선 빼봤는데 이전 거와 비교했을 때 들고갈 지 두고갈 지도 의논해보면 좋을 것 같아요!
- 세션 상세 조회: lecture, subLecture, Attendance 총 3번의 쿼리가 발생하는데 괜찮겠죠 ..!?
- 출석 정보 조회는 쿼리 최적화가 쉽지 않네요.. 😭 일단 올려놓고 계속 생각해보겟슴다 ㅠㅅㅠ
> [FIX] 세션 상세 조회 API 분리

- src/main/java/org/sopt/makers/operation/controller/AdminController.java
- src/main/java/org/sopt/makers/operation/dto/admin/LoginResponseDTO.java
- src/main/java/org/sopt/makers/operation/dto/admin/RefreshResponseDTO.java
- src/main/java/org/sopt/makers/operation/service/AdminService.java
- src/main/java/org/sopt/makers/operation/service/AdminServiceImpl.java
- src/main/java/org/sopt/makers/operation/util/Cookie.java
- #88
- 로그인에서 리프레시 토큰을 업데이트할때 service에서 한꺼번에 하도록 변경
- 리프레시 할때 refresh 토큰 유효성 검증을 service에서 하도록 변경
- 쿠키를 controller에서 중복된 코드로 사용하는게 아닌 모듈을 사용하도록 변경
- 컨트롤러 사이즈 괜찮은지 궁금합니다
> [REFACT] 로그인, 리프레시 service 작동 방식, 쿠키 모듈화

- src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
- src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
closed #99 
- 출석 점수 갱신 트리거가 있는데 설명(Opertaion)이 모호해서 "출석 종료" 워딩을 추가했습니다.
- 예외 처리 추가했습니다. (세션의 종료 시간이 지나기 전까지는 출석 종료가 불가합니다.)
> [FIX] 출석 종료 기능 수정: 설명 워딩 추가, 예외 처리 추가

- src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
- src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
- src/main/java/org/sopt/makers/operation/dto/lecture/LectureResponseDTO.java
- src/main/java/org/sopt/makers/operation/entity/SubLecture.java
- src/main/java/org/sopt/makers/operation/entity/lecture/Lecture.java
- src/main/java/org/sopt/makers/operation/entity/lecture/LectureStatus.java
- src/main/java/org/sopt/makers/operation/service/LectureService.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
- #110 
- 출석 관련 세션 상태 데이터를 추가했습니다.
- Lecture 엔티티에 LectureStatus 칼럼을 추가했습니다.
- Lecture: 상태 업데이트 및 세션 종료 메소드를 추가했습니다.
- 점수 갱신 트리거 메소드명을 finishLecture로 변경했습니다. (가독성, 명확성)
- 위 메소드의 로직을 변경 및 리팩토링 했습니다. (상태 값 활용, 구조 리팩토링)
- 세션 생성, 출석 시작, 세션 종료할 경우 해당 세션의 상태 값을 업데이트 했습니다. (BEFORE, FIRST, SECOND, END)
엔티티 칼럼을 추가함에 따라 dev DB에는 lectureStatus 칼럼을 추가해둔 상태입니다.
develop에서 main으로 머지할 때 prod에도 반영하겠습니다.
> [ADD] 출석 관련 세션 상태 데이터 추가

- src/main/java/org/sopt/makers/operation/controller/web/LectureController.java
- src/main/java/org/sopt/makers/operation/dto/lecture/LectureDetailResponseDTO.java
- src/main/java/org/sopt/makers/operation/service/LectureService.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
- closed #124 
- 세션 상세 조회 API 기능을 구현했습니다.
배열로 나오는 startDate와 endDate는 LocalDateTime 타입입니다!
> [FEAT] 세션 상세 조회 API

- src/main/java/org/sopt/makers/operation/entity/Member.java
- closed #129 
- END 상태의 세션 출석 정보만 점수 계산에 포함하도록 예외 처리 추가
> [FIX] 출석 점수 갱신 API 수정

- src/main/java/org/sopt/makers/operation/controller/ScheduleController.java
- src/main/java/org/sopt/makers/operation/repository/lecture/LectureCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/lecture/LectureRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/service/LectureService.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
- closed #151 
- 종료됐지만 상태 값이 업데이트 되지 않은 세션의 상태 값을 END 강제 업데이트합니다.
- 매주 일요일 자정(토요일에서 일요일 넘어가는)에 스케줄러를 실행합니다.
> [FEAT] 출석 자동 종료 스케줄러

- src/main/java/org/sopt/makers/operation/controller/web/MemberController.java
- src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/service/MemberService.java
- src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
- closed #155 
- 회원 리스트 조회에 페이지네이션 기능 추가했습니다.
- MemberRepository.search() 메소드를 사용하는 곳이 2곳이어서 인자 기준으로 두 메소드로 분리했습니다. (중복 코드 등 후에 리팩토링 진행하도록 하겠습니다!)
> [ADD] 회원 리스트 조회 페이지네이션 추가

- src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/repository/member/MemberRepository.java
- src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
- src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
- closed #162 
- 앱 토큰 인증시 현재 기수 필터링을 하지 않고 있었습니다
- 여러기수를 진행한 OB의 경우 여러개의 값이 쿼리가 되어 오류가 발생
- 현재 기수의 정보만 가져오도록 함
> [FIX] 앱 토큰 유저 정보 획득시 현재 기수 필터링 되지 않는 오류

- src/main/java/org/sopt/makers/operation/common/ExceptionMessage.java
- src/main/java/org/sopt/makers/operation/common/ResponseMessage.java
- src/main/java/org/sopt/makers/operation/controller/web/AlarmController.java
- src/main/java/org/sopt/makers/operation/dto/alarm/AlarmRequestDTO.java
- src/main/java/org/sopt/makers/operation/dto/alarm/AlarmResponseDTO.java
- src/main/java/org/sopt/makers/operation/dto/alarm/AlarmsResponseDTO.java
- src/main/java/org/sopt/makers/operation/entity/alarm/Alarm.java
- src/main/java/org/sopt/makers/operation/repository/AlarmRepository.java
- src/main/java/org/sopt/makers/operation/repository/alarm/AlarmCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepository.java
- src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/service/AlarmService.java
- src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
- closed #172 
- 알림 생성 API
- 알림 리스트 조회 API
- 알림 상세 조회 API
- 알림 삭제 API
아래와 같은 조건으로 API를 설계했어요. 참고 부탁드려요~!
- 알림 생성 시 status 값의 디폴트는 BEFORE
- part와 isActive는 하나만 null 값일 수 없음
- 리스트 조회에서 generation, part, status 필터링 (query 값이 null로 들어오면 전체 조회)
> [FEAT] 알림 어드민 API 개발

- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
- closed #195 
- 회원의 플그 id가 null일 경우 알림 발송에 실패
- null 처리를 추가하여 이슈 해결
> [FIX] 알림 발송 대상 회원 플그 id null 처리 추가

- src/main/java/org/sopt/makers/operation/dto/alarm/AlarmsResponseDTO.java
- src/main/java/org/sopt/makers/operation/dto/attendance/AttendancesResponseDTO.java
- src/main/java/org/sopt/makers/operation/dto/member/MembersResponseDTO.java
- src/main/java/org/sopt/makers/operation/repository/alarm/AlarmCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/alarm/AlarmRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/attendance/AttendanceRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/repository/member/MemberCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/member/MemberRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
- src/main/java/org/sopt/makers/operation/service/AttendanceService.java
- src/main/java/org/sopt/makers/operation/service/AttendanceServiceImpl.java
- src/main/java/org/sopt/makers/operation/service/MemberService.java
- src/main/java/org/sopt/makers/operation/service/MemberServiceImpl.java
- closed #203 
- 클라이언트 요청입니다.
- Pageable 파라미터가 포함된 URI 기준으로, 조건과 일치하는 데이터의 총 개수 데이터를 추가했습니다.
- totalCount 필드명 통일
- List 타입 자체로 응답하는 API는 새로운 DTO를 생성하여 한 번 감쌌습니다.
- 로컬 기준 테스트 진행했습니다.
- 용택 담당이었던 전체 회원 조회도 요청에 포함되는 API 여서 제 나름대로 수정했습니다. 문제가 있다면 알려주세요! 🙇‍♀️
> [ADD] 응답 데이터 총 개수 추가

- scripts/switch.sh
- closed #204 
- certbot webroot 방식을 사용하는데, cron이 지속적으로 실패함
- webroot는 nginx단에 http요청을 보내서 유효성을 확인해서 인증하는 방식
- 해당 명령어 때문에 80포트 요청이 nginx를 안타고 바로 8081,8082 포트로 리다이렉트가 됨
- 인증서가 인증이 안되어 갱신이 안되는 이슈가 발생
- 해당 명령어 무효화 시키고 실행했을 때 갱신이 잘되긴 합니다.
- 이유가 타당한지 의논 필요!
> [FIX] 포트 포워딩 삭제

- src/main/java/org/sopt/makers/operation/config/RestTemplateConfig.java
- src/main/java/org/sopt/makers/operation/controller/web/AlarmController.java
- src/main/java/org/sopt/makers/operation/dto/alarm/AlarmSenderDTO.java
- src/main/java/org/sopt/makers/operation/external/api/AlarmSender.java
- src/main/java/org/sopt/makers/operation/external/api/AlarmSenderImpl.java
- src/main/java/org/sopt/makers/operation/external/api/PlayGround.java
- src/main/java/org/sopt/makers/operation/external/api/PlayGroundServer.java
- src/main/java/org/sopt/makers/operation/external/api/PlayGroundServerImpl.java
- src/main/java/org/sopt/makers/operation/service/AlarmService.java
- src/main/java/org/sopt/makers/operation/service/AlarmServiceImpl.java
- src/main/java/org/sopt/makers/operation/service/LectureServiceImpl.java
- closed #209 
- 외부 API 인터페이스를 분리했습니다. (알림 전송, 비활동 회원 조회)
- (특히 인수인계 과정에서) 유지보수와 가독성을 위해 외부 API를 따로 관리하는 패키지 및 인터페이스로 분리했습니다.
- RestTemplate은 Bean으로 등록했습니다. DI를 적용함으로써 의존도를 낮추기 위해 고려했습니다.
- 변수, 메서드 이름을 변경했습니다. `직관적인 이름인가?` `전체적인 코드 스타일에 통일되는가?`를 위주로 우선 개인적으로 판단하여 변경했습니다. 다른 의견이 있다면 리뷰 부탁드려요!
- 인터페이스 분리 과정에서 단일 책임 원칙을 적용하기 위해 한 메서드가 하나의 기능을 담당하도록 최대한 분리하고자 했습니다.
- 우선 제 담당이 아니었던 코드에 대해 리팩토링 작업을 수행하여 죄송해요. 곧 있을 인수인계를 효율적으로 대처하고 싶은 생각에서 좀 더 유지보수에 유리한 설계 구조를 생각하며 적용하고자 했어요. 해당 작업과 관련해서 용택님의 의견을 적극적으로 수용하도록 하겠습니다!
- 외부 API를 별도의 인터페이스로 분리하는 방식에 대한 의견이 궁금해요.
- 특히 변경된 변수, 메서드 이름에 대해서 생각하시는 의견이 궁금해요.
- 그 외 다른 의견, 추가적인 의견, 궁금한 점 등등 모두 편하게 리뷰로 알려주시면 감사하겠습니다!
> [FIX] 외부 API 인터페이스 분리

- src/main/java/org/sopt/makers/operation/controller/app/AppScheduleController.java
- src/main/java/org/sopt/makers/operation/dto/schedule/SchedulesResponseDTO.java
- src/main/java/org/sopt/makers/operation/entity/schedule/Schedule.java
- src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleCustomRepository.java
- src/main/java/org/sopt/makers/operation/repository/schedule/ScheduleRepositoryImpl.java
- src/main/java/org/sopt/makers/operation/service/ScheduleServiceImpl.java
...
- 슬랙으로 전달해준 2가지 사항 반영했어요!
- DTO 내 날짜 요일 정보 추가 (디자인을 참고해서 한글 줄임 형식으로 들어가는 것 확인하고, 같은 형식으로 일치시켰어요.)
- DTO 형식 List로 변경 (Map 형식에서 List 형식으로 변경했어요.)
- (현재 슬랙으로 논의 중이긴 하나) 일정 데이터가 없는 날짜 데이터까지 내려주면 비효율적인 응답 데이터가 많아질 것으로 생각하여 일정이 존재하는 날짜만 내려주는 것으로 변경했어요. 차후 논의 내용이 다른 방향으로 달라지면 되돌려놓도록 할게요!
- startDate 기준으로 오름차순, 날짜 기준으로 오름차순 정렬 반영했어요.
- Scheduler 엔티티의 `LocalDateTime date` 칼럼은 어디서 사용되는 값일까요?? startDate로 충분히 판단 가능할 것 같아 해당 칼럼은 의미가 없다고 생각해서 개인적으로 삭제하는 방향이 좋을 것 같아요. 이 부분에 대해서 용택님 의견도 부탁드려요! 우선 삭제하진 않고 TODO 남겨놓았어요.
- 기간이 1, 2일 넘어가는 일정 고려하여 비즈니스 로직 추가 작업 수행했어요.
- 그 외 모호한 메서드명은 좀 더 구체적으로 보완하고, 메서드 분리 작업 수행했어요.
사소한 의견부터 큰 의견까지 자유롭게 리뷰 부탁드려요 :)
의논 일치 및 반영 후 PR 머지하도록 할게요!
아래 API 테스트 결과
```
{
"success": true,
"message": "일정 리스트 조회 성공",
"data": {
"dates": [
{
"date": "2023-12-23",
"dayOfWeek": "토", …
```
> [ADD] PR 이어받아 추가 작업

- operation-common/src/main/java/org/sopt/makers/operation/code/failure/lecture/LectureFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/dto/BaseResponse.java
- operation-external/src/main/java/org/sopt/makers/operation/client/alarm/AlarmSenderImpl.java
- closed #249 
- Closes T-10697
iOS 무한 로딩 이슈 해결을 위해 Response DTO 내 `data` 필드 nullable 하게끔 롤백했습니다.
> [FIX] iOS 무한로딩 원인 DTO 롤백

- operation-domain/build.gradle
- operation-domain/src/main/java/org/sopt/makers/operation/attendance/domain/Attendance.java
- operation-domain/src/main/java/org/sopt/makers/operation/attendance/domain/SubAttendance.java
- operation-domain/src/main/java/org/sopt/makers/operation/lecture/domain/Lecture.java
- operation-domain/src/main/java/org/sopt/makers/operation/lecture/domain/SubLecture.java
- operation-domain/src/main/java/org/sopt/makers/operation/member/domain/Member.java
- operation-domain/src/test/java/org/sopt/makers/operation/attendance/domain/AttendanceGetScoreTest.java
- operation-domain/src/test/java/org/sopt/makers/operation/attendance/domain/AttendanceGetStatusTest.java
- operation-domain/src/test/java/org/sopt/makers/operation/dummy/AttendanceDummy.java
- operation-domain/src/test/java/org/sopt/makers/operation/dummy/LectureDummy.java
- operation-domain/src/test/java/org/sopt/makers/operation/dummy/MemberDummy.java
- operation-domain/src/test/java/org/sopt/makers/operation/dummy/SubAttendanceDummy.java
- operation-domain/src/test/java/org/sopt/makers/operation/dummy/SubLectureDummy.java
- closed #253 
- 이번에 출석 관련 로직이 수정됨에 따라서 추후에 또 수정할 일이 있을 때 빠르게 검사하기 위해서 테스트 코드를 추가했습니다.
- 단위 테스트시 도메인을 생성하기 위해서 실제 비즈니스 로직에 영향이 안가도록 도메인 내에 protected 생성자를 만든 후에 도메인 객체를 상속 받는 Dummy 객체를 만들었습니다.
- Attendance 도메인 내에 존재하는 getScore 함수와 getStatus 함수의 단위 테스트를 작성했습니다.
- 행사도 지각시 0.5 점을 부여하기 때문에 도메인 로직을 수정했습니다.
`@DisplayName` 테스트명이 괜찮은지 궁금합니다
> [TEST] 출석 관련 단위 테스트 추가 및 행사 출석 로직 수정

- .github/workflows/cd-dev.yml
- .github/workflows/ci.yml
- operation-api/build.gradle
- operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApi.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/dto/response/AuthorizationCodeResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthService.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthServiceImpl.java
- operation-api/src/main/java/org/sopt/makers/operation/common/handler/ErrorHandler.java
- operation-api/src/test/java/org/sopt/makers/operation/auth/api/AuthApiControllerTest.java
- operation-api/src/test/java/org/sopt/makers/operation/auth/service/AuthServiceTest.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/AuthFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/auth/AuthSuccessCode.java
- operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/AuthException.java
- operation-domain/src/main/java/org/sopt/makers/operation/auth/domain/Team.java
- operation-domain/src/main/java/org/sopt/makers/operation/auth/domain/TeamOAuthInfo.java
- operation-domain/src/main/java/org/sopt/makers/operation/auth/repository/TeamOAuthInfoRepository.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/domain/SocialType.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/repository/identityinfo/UserIdentityInfoRepository.java
- operation-external/build.gradle
- operation-external/src/main/java/org/sopt/makers/operation/client/social/AppleSocialLogin.java
- operation-external/src/main/java/org/sopt/makers/operation/client/social/GoogleSocialLogin.java
- operation-external/src/main/java/org/sopt/makers/operation/client/social/SocialLoginManager.java
- operation-external/src/main/java/org/sopt/makers/operation/client/social/dto/IdTokenResponse.java
- closed #258 
1. external 모듈 내 소셜 로그인 기능 구현
1. Auth Controller 내부에서 Social Login Manger를 이용하여 소셜 로그인을 진행하려 합니다.
추상화를 통해 공통된 로직을 분리하려 했으나, 해당 방식은 확장성을 방해한다고 생각하여
소셜 로그인 별로 class 를 만들었습니다.
[ex. 소셜 로그인 변경 or 소셜 로그인 중 open id 방식을 지원하지 않을 수 있음 ]
2. 비즈니스 로직
[c826462](https://github.com/sopt-makers/sopt-operation-backend/pull/260/commits/c8264627d1f381d459d7413d114e64e024e1c0f0) 해당 커밋 메시지처럼 구현했습니다..!
3. 플랫폼 인가 코드 저장을 위한 concurrent hash map
redis를 아직 사용하지 않기 때문에 concurrent hash map 내부에 인가코드를 저장했습니다.
해당 map은 플랫폼 인가 코드를 단 1회만 사용할 수 있도록 만들기 위해서 인가 코드를 잠시 저장하는 용도입니다.
`/token` API 시 인가 코드가 MAP에 있는지 확인 후, 해당 인가 코드를 제거할 것입니다.
4. 에러 메시지 및 함수 명 작성이 명시적인지 궁금합니다.
> T-10855 [feat] GET /authorize API 구현

- operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApi.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/dto/request/AccessTokenRequest.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/dto/response/TokenResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthService.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/service/AuthServiceImpl.java
- operation-api/src/main/java/org/sopt/makers/operation/common/config/ConcurrentHashMapConfig.java
- operation-api/src/test/java/org/sopt/makers/operation/auth/api/AuthApiControllerTest.java
- operation-api/src/test/java/org/sopt/makers/operation/auth/service/AuthServiceTest.java
- operation-api/src/test/java/org/sopt/makers/operation/jwt/JwtTokenProviderTest.java
- operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtTokenProvider.java
- operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtTokenType.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/AuthFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/auth/AuthSuccessCode.java
- closed #261 
- /token api 구현
기존에는 auth service 에서 플랫폼 인가코드를 생성하는 로직이 있었습니다.
개발 도중 기존에 만들어진 jwt token provider를 사용하면 코드 중복을 줄일 수 있겠다고 생각하여
Platform Code enum 값을 추가하여 플랫폼 인가코드를 발급하는 로직을 추가했습니다.
/token 테스트 코드를 작성할 때, hash map에 플랫폼 인가코드가 contain하는지 검증하는 로직을 테스트해야 했습니다.
기존에는 `= new Hashmap<>() ` 같이 설정했기 때문에 테스트 코드를 작성하는데 어려웠습니다.
이를 해결하기 위해 **Configuration을 통해 ConcurrentHashMap을 bean으로 등록**해 의존성을 주입받는 형태로 변경했고,
테스트 코드에서는 mockbean을 통해 테스트 가능하도록 만들었습니다.
클라이언트가 ATK가 만료되어 RTK를 통해 토큰을 갱신 받는 과정에서 grantType 과 refreshToken만 받고 있습니다.
clientId와 redirectUri를 claims에 넣어 검증하려 했으나, 
플레이그라운드에서 발급한 토큰이 모임에서 만료되었을 때, **토큰 내부의 clientId와 호출하는 팀(모임)의 clientId가 다르기 때문에** 위와 같은 검증이 제대로 이뤄지지 않을 것이라 판단했습니다.
따라서 grantType 과 refreshToken만 받아서 refreshToken이 만료되지 않았다면 다시 ATK, RTK를 반환하도록 구현하려하는데,
이 방식에 동의하는지 궁금합니다..!
> #261_T-10856 [feat] /token API 구현

- operation-api/src/main/java/org/sopt/makers/operation/auth/api/AuthApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/dto/response/AuthorizationCodeResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/auth/dto/response/RedirectUrlResponse.java
- operation-api/src/test/java/org/sopt/makers/operation/auth/api/AuthApiControllerTest.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/auth/AuthSuccessCode.java
- closed #270 
- redirect uri를 웹 로컬에 저장함으로써 웹은 로컬 관리까지 수반됐습니다.
플랫폼 인가코드와 함께 리다이렉션 uri를 합쳐서 redirect url 형태로 넘겨주면서 웹의 부담을 줄이기로 결정했습니다.
> #270 [fix] /authorize 명세 수정

- operation-api/src/main/java/org/sopt/makers/operation/common/handler/ErrorHandler.java
- operation-api/src/main/java/org/sopt/makers/operation/common/util/CommonUtils.java
- operation-api/src/main/java/org/sopt/makers/operation/user/api/UserApi.java
- operation-api/src/main/java/org/sopt/makers/operation/user/api/UserApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/user/dto/response/ActivityTotalVO.java
- operation-api/src/main/java/org/sopt/makers/operation/user/dto/response/UserActivityInfoResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/user/dto/response/UserInfoResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/user/dto/response/UserInfosResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/user/service/UserService.java
- operation-api/src/main/java/org/sopt/makers/operation/user/service/UserServiceImpl.java
- operation-api/src/test/java/org/sopt/makers/operation/user/api/UserApiControllerTest.java
- operation-api/src/test/java/org/sopt/makers/operation/user/service/UserServiceTest.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/UserFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/UserSuccessCode.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/ParameterDecodeCustomException.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/UserException.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/repository/UserRepository.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/repository/history/UserGenerationHistoryRepository.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/repository/identityinfo/UserIdentityInfoRepository.java
- operation-domain/src/test/java/org/sopt/makers/operation/user/repository/UserRepositoryTest.java
- closed #259 
- closes T-10858
<br/>
- Request Header에 있는 Platform Token 토큰 기반 Principal 값으로 **본인(단일 유저)에 대한 유저 정보**를 조회하는 API입니다.
- 각 SOPT makers 프로덕트 서버들이 클라이언트(요청자) 자신의 정보가 필요할 때 호출하여 사용합니다.
- Repository 레이어 & Service 레이어에 대한 Unit Test 또한 수행했습니다.
<br/>
<br/>
> 양이 조금 많은 점 양해부탁드립니다..호호
이전 기수부터 이어져온 DTO 생성자 전략이 Builder 를 적용하여 **static 생성 메서드**를 사용하는 구조입니다.(`@Builder(access=private)` & `public static {DTO Class} of(...)`) 
`@Builder(access=private)`을 통해
만약 외부에서 해당 객체를 생성할 수 있는 방법을 단 한가지로 제어하기 위함이라면
Builder를 사용하지 않고 `@...ArgsConstructor(access = AccessLevel.PRIVATE)`을 활용해  public static 생성자 메서드만 선언하는 것도 무관할 것이라고 생각했습니다.
```java
@NoArgsConstructor(access = AccessLevel.PRIVATE)
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@RequiredArgsConstructor(access = AccessLevel.PRIVATE)
public …
```
> [FEAT] GET  /internal/user/me API 구현

- .github/workflows/cd-dev.yml
- .github/workflows/cd-prod.yml
- .github/workflows/ci.yml
- operation-api/src/main/java/org/sopt/makers/operation/common/handler/ErrorHandler.java
- operation-api/src/main/java/org/sopt/makers/operation/common/util/PermissionValidator.java
- operation-api/src/main/java/org/sopt/makers/operation/user/api/UserApi.java
- operation-api/src/main/java/org/sopt/makers/operation/user/api/UserApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/user/dto/request/UserActivityModifyRequest.java
- operation-api/src/main/java/org/sopt/makers/operation/user/dto/request/UserModifyRequest.java
- operation-api/src/main/java/org/sopt/makers/operation/user/service/UserService.java
- operation-api/src/main/java/org/sopt/makers/operation/user/service/UserServiceImpl.java
- operation-api/src/test/java/org/sopt/makers/operation/user/api/UserApiControllerTest.java
- operation-api/src/test/java/org/sopt/makers/operation/user/service/UserServiceTest.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/PermissionFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/UserFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/UserSuccessCode.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/PermissionException.java
- operation-domain/build.gradle
- operation-domain/src/main/java/org/sopt/makers/operation/user/dao/UserActivityInfoUpdateDao.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/dao/UserPersonalInfoUpdateDao.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/domain/Part.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/domain/Team.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/domain/User.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/domain/UserGenerationHistory.java
- operation-domain/src/main/java/org/sopt/makers/operation/user/repository/history/UserGenerationHistoryRepository.java
- operation-domain/src/test/java/org/sopt/makers/operation/DatabaseCleaner.java
- operation-domain/src/test/java/org/sopt/makers/operation/user/repository/UserRepositoryTest.java
- closed #276 
- closes T-10859
> 기능
- Request Body 내 User ID에 해당하는 단일 유저에 대한 정보를 변경하는 API입니다.
- Repository 레이어 & Service 레이어에 대한 Unit Test 또한 수행했습니다.
- Service Layer : Exception 발생 여부 확인
- Repository(Domain) Layer : `@Dynamic Update` 정상 적용 여부 & 정상 데이터 수정 반영 여부
- `@Dynamic Update` 정상 적용 여부의 경우, `application-test.yml` 내 `logging.level.org.hibernate.SQL.DEBUG`로 설정하여 동적 쿼리 생성 여부를 확인하는 방식으로 진행했습니다.
<br/>
> 빌드/배포
- CI/CD Script Step이 추가되었습니다.
- CI 및 CD 과정에서 Test YAML 파일 생성 Step을 추가했습니다.
- Domain Test에서 사용되는 DB 환경을 분리하기 위해 `@Profile`을 통해 특정 profile에 해당하는 yaml 파일을 활용하여 테스트가 빌드되도록 설정했습니다.
- 빌드 과정에서 `application-test.yml` 파일을 생성하여
- `application-test.yml`의 경우, 본 `sopt-operation-backend` 레포 Actions Secret 값으로 추가해두었습니다.
- [노션](https://www.notion.so/sopt-makers/application-test-yml-8f6451d741cb4a23bc5 …
> [FEAT] PUT /internal/user API 구현

- operation-api/src/main/java/org/sopt/makers/operation/common/handler/ErrorHandler.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/request/BannerRequest.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/request/ImageExtension.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/request/ImageType.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
- operation-api/src/main/resources/application-dev.yml
- operation-api/src/main/resources/application-test.yml
- operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/ExternalFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
- operation-common/src/main/java/org/sopt/makers/operation/config/ValueConfig.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/ExternalException.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/Banner.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/BannerImage.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ContentType.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ImageExtension.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/ImageType.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishPeriod.java
- operation-external/build.gradle
- operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3Manager.java
- operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3Service.java
- operation-external/src/main/java/org/sopt/makers/operation/client/s3/S3ServiceImpl.java
- closed #289
- AWS S3 bucket에 이미지 업로드 시 pre signed url을 사용할 수 있도록 했습니다
- 다음과 같이 배너명과 배너를 생성한 일자, 이미지 유형 등이 이름에 포함됩니다
```
{
"success": true,
"message": "이미지 업로드 pre signed url 조회에 성공했습니다",
"data": {
"presigned-url": "https://makers-banner.s3.ap-northeast-2.amazonaws.com/birthday/2024-12-23_happy%28mo%29.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20241222T171034Z&X-Amz-SignedHeaders=host&X-Amz-Expires=1200&X-Amz-Credential=AKIAVQPX6FSLFAUMBS55%2F20241222%2Fap-northeast-2%2Fs3%2Faws4_request&X-Amz-Signature=b27ec52a28f7240a371ab22de0ae5d9a5162013d47d625d2362ebaaff5fd2892",
"filename": "birthday/2024-12-23_happy(mo).png" // 클라이언트에서 다시 서버로 보내줄 값
}
}
```
- pre signed url을 통한 이미지 업로드도 확인 완료했습니다
- 배너 생성 API도 확인 완료했습니다
- 배너 수정을 위해 S3에서 이미지를 삭제하는 로직을 미리 구현했습니다
*동규오빠 작업 머지 이후의 변경사항*
1. banner …
> [FEAT/#289] 배너 이미지 pre-sigend url 조회 및 배너 생성 API 구현

- operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
- operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/BannerImage.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/repository/BannerRepository.java
- closed #290 
- 배너 삭제 기능과 외부 배너 조회 기능을 구현했습니다. 
[배너 삭제](https://www.notion.so/sopt-makers/d8a77121bc1d4b13b1c9fd9f159a768e?pvs=4)
[외부 배너 조회](https://www.notion.so/sopt-makers/0bdc33f5dd98486da2bf851cde640b6b?pvs=4)
배너 이미지 조회는 Embedded된 객체 내부에서 switch 문을 통해 해당하는 플랫폼 이미지를 반환하도록 구현했습니다.
> [FEAT/#290] 배너 삭제 & 외부 배너 조회 기능 구현

- .github/workflows/cd-dev.yml
- .github/workflows/ci.yml
- Dockerfile
- operation-api/build.gradle
- operation-domain/src/test/java/org/sopt/makers/operation/banner/BannerTest.java
- operation-domain/src/test/java/org/sopt/makers/operation/banner/PublishPeriodTest.java
- closed #295 
- CI 
- docker 기반 Build 방식으로 변경했습니다.
- `operation-api` 모듈의 `build.gradle` 내에 build profile parameter(`-Pprofile`)에 따라 yaml 파일을 선택할 수 있도록 했습니다.
- test yaml의 경우, 변경 필요성이 존재하지 않기 때문에 제외 했습니다.
- CD
- EC2 SSH 접속 및 배포 명령 방식으로 변경했습니다.
기존 CI의 경우, Local에서의 테스트 통과 후 PR을 생성하는 컨벤션에 의존한 채 Script 내에서는 테스트를 제외하고 Build 했습니다.
하지만 신뢰성 보장 후에 Merge 및 배포되는 것이 바람직하다고 판단하여 `-x test` 명령을 제거했습니다.
<br/>
<작업>
- Code Deploy를 활용하여 Deployment 생성 & EC2 내 Code Deploy Agent 로 배포 실행되는 방식에서 Github Actions에서 SSH로 직접 접속하여 배포를 실행하도록 변경했습니다.
- EC2 내 저장 공간을 확보하기 위해 Java(Docker 기반 배포이기 때문에 불필요) & Ruby(Code Deploy Agent)를 제거했습니다.
<이유>
- 배포 과정에서 EC2 내에 실행되는 리소스 및 프로세스를 최소화
- 배포 과정 가시화 (인수인계 효율, 문서화 용이)
- AWS 서비스 의존성 절감
<우려점>
- Github Actions 내에서 사용하는 `appleboy`라이브러리 변경에 대한 의존성 우려
> [REFACTOR/#295] 배포 방식 변경

- operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
- operation-api/src/test/java/org/sopt/makers/operation/web/banner/api/BannerApiControllerTest.java
- closed #299
- 배너 생성 작업에 대한 컨트롤러 단 테스트코드를 작성했습니다
- 오빠들이 작업한 API는 모두 `when(bannerService.getBannerDetail(MOCK_BANNER_ID)).thenReturn(mockBannerDetail);` 부분에서 모킹한 getBannerDetail 메서드를 사용하고 있는데요 이 부분이 현재 모든 테스트 실행 이전에 동작하는 `@BeforeEach`에 정의되어 있습니다
- 그러나 제 API는 생성과 관련되어 있기 때문에 해당 부분이 필요 없다는 생각이 들었습니다 그래서 서비스 단 모킹 코드를 각 테스트에서 진행하는 것은 어떤지 궁금합니다
- 현재는 제 코드에서 이미 모킹이 진행된다는 가정하에 getBannerDetail을 사용하긴 했는데, 이 과정 없이 givenBannerDetail의 값과 비교하는 과정만으로도 충분한 테스트가 진행된다고 생각해요 오빠들의 생각이 궁금합니다!
- 그리고 현욱오빠 테스트코드에서 (DELETE) Banner Detail 부분에 mockBannerDetail 변수는 필요없는 코드인 것 같은데 어떻게 생각하시나요?
> [TEST/#299] 배너 생성 컨트롤러 테스트코드 작성

- operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApi.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/api/BannerApiController.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/dto/response/BannerResponse.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerService.java
- operation-api/src/main/java/org/sopt/makers/operation/web/banner/service/BannerServiceImpl.java
- operation-api/src/main/resources/data/insert-get-banners-data.sql
- operation-api/src/test/java/org/sopt/makers/operation/web/banner/service/BannerServiceTest.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/BannerFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/code/success/web/BannerSuccessCode.java
- operation-common/src/main/java/org/sopt/makers/operation/config/TimeConfig.java
- operation-domain/src/main/java/org/sopt/makers/operation/banner/domain/PublishStatus.java
- operation-domain/src/test/java/org/sopt/makers/operation/banner/BannerTest.java
- operation-domain/src/test/java/org/sopt/makers/operation/banner/PublishPeriodTest.java
- closed #297
- 배너 목록 조회 기능 구현
현재 구현된 방향성은 아래와 같습니다.
- Service 인터페이스에 "정렬 기준"(Sort Criteria) / "분류 기준"(Filter Criteria) Enum 클래스를 선언했습니다.
- 외부의 입력값에 대해 Service 구현체 내부에서 변환하는 것은 "책임이 분리되지 않은 것"이라고 판단했습니다.
- Controller 단에서 "요청 값 → 비즈니스 로직 가용 값" 변환이 필요하다고 판단했습니다.
- Criteria Enum의 경우, `#fromParameter`라는 비즈니스 로직 가용 값으로 전환하는 static method를 제공합니다.
<br/>
주로 요청 시점 기반 동적 연산이 필요한 경우, `LocalDate.now()`/`LocalDateTime.now()`를 통해 현재 시간에 대한 데이터를 조회하게 됩니다.
하지만 위와 같이 구현한 경우, 특정 날짜 값과의 연산이 필요한 기능에 대해 Test를 진행하면 에러가 발생할 확률이 높아진다고 생각합니다.
(실제로 CI 단계에서 에러가 발생하는 것을 발견했습니다.)
이에 따라 `Clock` 객체 주입을 통한 `LocalDate.now()`/`LocalDateTime.now()` 호출 방식으로 변경해 해결했습니다.
이로써 얻게 된 효용은 아래와 같습니다.
- 테스트 진행 시, 테스트에서 의도한 기준 날짜 기반으로 테스트를 진행할 수 있습니다.
- 현재 시스템 상의 시간에 의존적인 코드 구현을 방지할 수 있습니다.
<br/>
현재 구현 방식은 후자인 "**Stream 중간 연산** …
> [FEAT/#297] 배너 목록 조회 기능 구현

- Dockerfile
- operation-external/src/main/java/org/sopt/makers/operation/client/alarm/InstantAlarmSender.java
- closed #340 
- related to #340 
- RestTemplate으로 알림 서버에 요청을 보낼 때 Content-Type 헤더에 UTF-8 charset을 추가했습니다.
- Docker 실행 시 JVM 인코딩을 utf-8로 설정했습니다 (dockerfile 수정)
- 알림 요청 시 instantRequest 에 비어있는 필드에 접근할 때 NullPointerException이 발생하여 예외처리를 추가했습니다
로컬에서는 알림 깨짐없이 잘 가는 것 확인했습니다!
> [FIX] 알림 한글 깨짐 이슈 

- build.gradle
- operation-api/src/main/java/org/sopt/makers/operation/common/config/SwaggerConfig.java
- closed #343 
- related to #343
- `to-be` : member 테이블에서 회원 조회 시 Part에 회장/부회장/총무/메이커스 팀장 등 정의되지 않은 문자열이 들어가 있는 케이스가 있어 500 에러가 발생했습니다
- 이를 해결하기 위해 dev/prod 테이블 데이터를 확인했으며 dev 환경에서만 해당 데이터가 존재하고 있음을 확인했고, dev에서 해당 데이터를 삭제하였습니다
- 또한 localhost에서 swagger 테스트를 진행할 수 없어 관련 설정을 수정해주었습니다
> [FIX] 알림 어드민: 활동기수 + 전체 파트로 전송 시 dev 테이블에서 존재하지 않는 Part가 존재하지 않는 문제 해결

- .github/PULL_REQUEST_TEMPLATE.md
- operation-api/src/main/java/org/sopt/makers/operation/OperationApplication.java
- operation-api/src/main/java/org/sopt/makers/operation/test/UserInfoController.java
- operation-api/src/main/resources/application-dev.yml
- operation-auth/build.gradle
- operation-auth/src/main/java/org/sopt/makers/operation/authentication/MakersAuthentication.java
- operation-auth/src/main/java/org/sopt/makers/operation/filter/JwtAuthenticationFilter.java
- operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwkProvider.java
- operation-auth/src/main/java/org/sopt/makers/operation/jwt/JwtAuthenticationService.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/ClientFailure.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/JwkFailure.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/JwtFailure.java
- operation-common/src/main/java/org/sopt/makers/operation/code/failure/auth/PermissionFailureCode.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/BaseException.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/ClientException.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/JwkException.java
- operation-common/src/main/java/org/sopt/makers/operation/exception/JwtException.java
- operation-external/build.gradle
- operation-external/src/main/java/org/sopt/makers/operation/client/auth/AuthClient.java
- operation-external/src/main/java/org/sopt/makers/operation/client/auth/AuthClientProperty.java
- operation-external/src/main/java/org/sopt/makers/operation/config/AuthWebClientConfig.java
- related to #357 
- 앱에서 어드민으로 api 호출
- jwt 필터 작동 → jwt 서비스  authenticate(토큰) 실행
1. *JWT 파싱 (header에서 kid 추출)*
2. *JWK Provider에서 공개키 조회* `getPublicKey`
1. 캐시에서 퍼블릭 키 조회
1. 실패시 `resolvePublicKey` 실행 
2. 인증서버로 부터 JWK 조회 `loadJwkSet()` → `authClient.getJwk()`
3. verifyWithRetry를 통해 서명 및 클레임 검증 (재시도 포함)
1. 검증된 JWTClaimSet 반환( **내부에 유저 데이터** )
4.  *검증된 JWTClaimsSet으로부터 MakersAuthentication} 생성*
**1. JwtAuthenticationFilter → jwtAuthenticationService**
-  Authorization 헤더 토큰 추출
- kid 및 issuer 존재 확인
- authenticate(token) 실행
**2. jwtAuthenticationService → JwkProvider**
- JWT 파싱 (header에서 kid 추출)
- JWK Provider에서 공개키 조회 getPublicKey(kid) 실행
**2.JwkProvider → AuthClient(캐시 Miss)**
- 인증 서버로부터 JWK(JSON Web Key) Set 조회 (공개키들 데이터 포함)
- kid로 특정 JWK 찾아서 반환
**4.  JwkProvider -> …
> [FEAT] 인증중앙화 
